---
- hosts: idrac
  connection: local
  name: Check LC Ready Status
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Check LC Ready Status
    idrac_lifecycle_controller_status_info:
       idrac_ip:   192.168.0.46
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
