---
- hosts: idrac
  connection: local
  name: Configure iDRAC syslog attributes
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Configure iDRAC syslog attributes
    idrac_syslog:
       idrac_ip:   192.168.0.46
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       share_name: "{{ playbook_dir }}"
       syslog: "Disabled"