---
- hosts: idrac
  connection: local
  name: Reset iDRAC
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Reset iDRAC
    idrac_reset:
       idrac_ip:   192.168.0.46
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"

    tags:
      - idrac_reset